version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  api:
    build: ./backend
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/recipes   # << same network, use service name
      - JWT_SECRET=${JWT_SECRET}
    ports: ["8080:8080"]
    depends_on: [mongo]
    restart: unless-stopped

volumes:
  mongo_data: